import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-gb">
      {/* <meta
        name="google-adsense-account"
        content="ca-pub-2108937914858989"
      ></meta> */}
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
      <script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2108937914858989"
        crossorigin="anonymous"
      ></script>
    </html>
  );
}
